[[appendix-license]]
== Creative Commons License

This work is licensed under a Creative Commons
Attribution, Non-commercial, No Derivative Works 3.0 United States
license. For more information about this license, see
http://creativecommons.org/licenses/by-nc-nd/3.0/us/[http://creativecommons.org/licenses/by-nc-nd/3.0/us/]. You
are free to share, copy, distribute, display, and perform the work
under the following conditions:

* You must attribute the work to Sonatype, Inc. with a link to
   http://www.sonatype.com[http://www.sonatype.com].

If you redistribute this work on a web page, you must include the
following link with the URL in the about attribute listed on a single
line (remove the backslashes and join all URL parameters):

----
<div xmlns:cc="http://creativecommons.org/ns#" 
     about="http://creativecommons.org/license/results-one?q_1=2&q_1=1\
            &field_commercial=n&field_derivatives=n&field_jurisdiction=us\
            &field_format=StillImage&field_worktitle=Repository%3A+\Management\
            &field_attribute_to_name=Sonatype%2C+Inc.\
            &field_attribute_to_url=http%3A%2F%2Fwww.sonatype.com\
            &field_sourceurl=http%3A%2F%2Fwww.sonatype.com%2Fbook\
            &lang=en_US&language=en_US&n_questions=3">
    <a rel="cc:attributionURL" property="cc:attributionName" 
       href="http://www.sonatype.com">Sonatype, Inc.</a> / 
    <a rel="license" 
       href="http://creativecommons.org/licenses/by/3.0/us/">
        CC BY 3.0</a>
</div>
----

When downloaded or distributed in a jurisdiction other than the United
States of America, this work shall be covered by the appropriate
ported version of Creative Commons Attribution, NC, ND Works 3.0 license for the specific jurisdiction. If the
Creative Commons Attribution, NC, ND version
3.0 license is not available for a specific jurisdiction, this work
shall be covered under the Creative Commons
Attribution, NC, ND version 2.5 license for
the jurisdiction in which the work was downloaded or distributed. A
comprehensive list of jurisdictions for which a Creative Commons
license is available can be found on the Creative Commons
International web site at
http://creativecommons.org/international[http://creativecommons.org/international].

If no ported version of the Creative Commons license exists for a
particular jurisdiction, this work shall be covered by the generic,
unported Creative Commons Attribution, NC, ND version 3.0 license available from
http://creativecommons.org/licenses/by/3.0/[http://creativecommons.org/licenses/by/3.0/].
