[[preface-1]]
== Preface

Maven is a build tool, a project management tool, an abstract
container for running build tasks. It is a tool that has shown itself
indispensable for projects that graduate beyond the simple and need to
start finding consistent ways to manage and build large collections of
interdependent modules and libraries which make use of tens or
hundreds of third-party components. It is a tool that has removed much
of the burden of 3rd party dependency management from the daily work
schedule of millions of engineers, and it has enabled many
organizations to evolve beyond the toil and struggle of build
management into a new phase where the effort required to build and
maintain software is no longer a limiting factor in software design.

This work is the first attempt at a comprehensive title on Maven. It
builds upon the combined experience and work of the authors of all
previous Maven titles, and you should view it not as a finished work
but as the first edition in a long line of updates to follow. While
Maven has been around for a few years, the authors of this book
believe that it has just begun to deliver on the audacious promises it
makes. The authors, and company behind this book,
http://www.sonatype.com[Sonatype], believe that the publishing of this
book marks the beginning of a new phase of innovation and development
surrounding Maven and the software ecosystem that surrounds it.

=== Acknowledgements

Sonatype would like to thank the following contributors. The people
listed below have provided feedback which has helped improve the
quality of this book. Thanks to Raymond Toal, Steve Daly, Paul Strack,
Paul Reinerfelt, Chad Gorshing, Marcus Biel, Brian Dols, Mangalaganesh
Balasubramanian, Marius Kruger, Chris Maki, Matthew McCollough, Matt
Raible, and Mark Stewart. Special thanks to Joel Costigliola for
helping to debug and correct the Spring web chapter. Stan Guillory was
practically a contributing author given the number of corrections he
posted to the book's Get Satisfaction. Thank you Stan. Special thanks
to Richard Coasby of Bamboo for acting as the provisional grammar
consultant.

Thanks to our contributing authors including Eric Redmond.

Thanks to the following contributors who reported errors either in an
email or using the Get Satisfaction site: Paco Soberón, Ray Krueger,
Steinar Cook, Henning Saul, Anders Hammar, "george_007", "ksangani",
Niko Mahle, Arun Kumar, Harold Shinsato, "mimil", "-thrawn-", Matt
Gumbley. If you see your Get Satisfaction username in this list, and
you would like it replaced with your real name, send an email to
mailto:book@sonatype.com[book@sonatype.com].

Special thanks to Grant Birchmeier for taking the time to proofread
portions of the book and file extremely detailed feedback via
GetSatisfaction.

=== How to contribute
The source code for this book can be found on the
https://github.com/sonatype/maven-example-en[official GitHub repository].
