[[preface-copyright]]
== Copyright

Copyright © 2011 Sonatype, Inc.

Online version published by Sonatype, Inc.

This work is licensed under a Creative Commons
Attribution, Non-Commercial, No Derivative Works 3.0 United States
license. For more information about this license, see
http://creativecommons.org/licenses/by-nc-nd/3.0/us/[http://creativecommons.org/licenses/by-nc-nd/3.0/us/].

Nexus™, Nexus Professional™, Matrix™, Matrix Professional™, Sonatype
Professional™, all Matrix-related logos, and all Nexus-related logos
are trademarks or registered trademarks of Sonatype, Inc., in the
United States and other countries.

Java™, all Java-based trademarks and logos, Hudson™, and all
Hudson-based trademarks and logos are trademarks or registered
trademarks of Oracle, Inc., in the United States and other countries.

IBM® and WebSphere® are trademarks or registered trademarks of
International Business Machines, Inc., in the United States and other
countries.

Eclipse™ is a trademark of the Eclipse Foundation, Inc., in the United
States and other countries.

Apache and the Apache feather logo are trademarks of The Apache
Software Foundation.

Linux® is the registered trademark of Linus Torvalds in the U.S. and
other countries.

Many of the designations used by manufacturers and sellers to
distinguish their products are claimed as trademarks. Where those
designations appear in this book, and Sonatype, Inc. was aware of a
trademark claim, the designations have been printed in caps or initial
caps.

While every precaution has been taken in the preparation of this book,
the publisher and authors assume no responsibility for errors or
omissions, or for damages resulting from the use of the information
contained herein.
